package cn.wj.android.cashbook.core.design.theme

import androidx.compose.ui.graphics.Color

/**
 * 颜色
 */
val md_theme_light_primary = Color(0xFF00696F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF72F5FF)
val md_theme_light_onPrimaryContainer = Color(0xFF002022)
val md_theme_light_secondary = Color(0xFF765A00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDF96)
val md_theme_light_onSecondaryContainer = Color(0xFF251A00)
val md_theme_light_tertiary = Color(0xFFA04111)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDBCD)
val md_theme_light_onTertiaryContainer = Color(0xFF360F00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFDFC)
val md_theme_light_onBackground = Color(0xFF191C1C)
val md_theme_light_surface = Color(0xFFFAFDFC)
val md_theme_light_onSurface = Color(0xFF191C1C)
val md_theme_light_surfaceVariant = Color(0xFFDAE4E5)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4849)
val md_theme_light_outline = Color(0xFF6F797A)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F1)
val md_theme_light_inverseSurface = Color(0xFF2D3131)
val md_theme_light_inversePrimary = Color(0xFF44D9E4)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00696F)
val md_theme_light_outlineVariant = Color(0xFFBEC8C9)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF44D9E4)
val md_theme_dark_onPrimary = Color(0xFF00363A)
val md_theme_dark_primaryContainer = Color(0xFF004F54)
val md_theme_dark_onPrimaryContainer = Color(0xFF72F5FF)
val md_theme_dark_secondary = Color(0xFFF1C036)
val md_theme_dark_onSecondary = Color(0xFF3E2E00)
val md_theme_dark_secondaryContainer = Color(0xFF5A4400)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDF96)
val md_theme_dark_tertiary = Color(0xFFFFB597)
val md_theme_dark_onTertiary = Color(0xFF591D00)
val md_theme_dark_tertiaryContainer = Color(0xFF7E2C00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBCD)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1C)
val md_theme_dark_onBackground = Color(0xFFE0E3E3)
val md_theme_dark_surface = Color(0xFF191C1C)
val md_theme_dark_onSurface = Color(0xFFE0E3E3)
val md_theme_dark_surfaceVariant = Color(0xFF3F4849)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC8C9)
val md_theme_dark_outline = Color(0xFF899393)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1C)
val md_theme_dark_inverseSurface = Color(0xFFE0E3E3)
val md_theme_dark_inversePrimary = Color(0xFF00696F)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF44D9E4)
val md_theme_dark_outlineVariant = Color(0xFF3F4849)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF00BDC7)
